### PR TITLE
Refactored Code to support Assistant V2

### PR DESCRIPTION
**Pull request by stevenpkg**
* API code changes to Assistant to support session id
* Update context to latest version

### CODE REVIEW

**Comment by stevenpkg** [comment]
Adding @Oliver-I

**Comment by germanattanasio** [comment]
@stevenpkg can you update the README.md with the new instructions?
I would like for you to also test this with an app running in the IBM Cloud rather than locally so that we can be sure it will work as expected

**Comment by stevenpkg** [comment]
@germanattanasio you can test a dev version here

http://watson-assistant-intermediate-dev.mybluemix.net/

What changes to the readme would you like to see done?

**Comment by germanattanasio** [comment]
If you can say that this demo is using Assistant V2(link to the documentation) and to access the V1 use this url: [v1.1.0](https://github.com/watson-developer-cloud/assistant-intermediate/releases/tag/v1.1.0)

**Comment by stevenpkg** [comment]
@germanattanasio will make the changes you requested. Also can we keep a V1 snapshot/version so anyone that want to look at V1 code can.

**Comment by Oliver-I** [comment]
@stevenpkg I have updated the readme file on your branch.

@germanattanasio we always test on the cloud using dev UIs to see how the system reacts within the cloud.

**Comment by germanattanasio** [comment]
@stevenpkg All the releases are stored in the `Releases` tab https://github.com/watson-developer-cloud/assistant-intermediate/releases

This will be a major release so we will start with `2.0.0

**Pull request merged**
